/* ============================================================
   NZTA Class 1 Theory Test — Question Bank
   ============================================================
   This file is the single source of truth for quiz content.
   To add more questions later, just push more objects into
   the QUESTION_BANK array below — the app will pick them up
   automatically, no other code changes needed.

   Schema for each question:
   {
     id: number,                      // unique identifier
     type: "single" | "judge",        // single-choice or true/false
     question: string,                // English question text
     options: string[],               // 4 options for "single", [] for "judge"
     answer: "A"|"B"|"C"|"D" | true|false,
     analysis: string,                // explanation citing the Road Code
     topic: string                    // category tag, used for filtering
   }
   ============================================================ */

const QUESTION_BANK = [
  { id: 51, type: "single", topic: "Roundabout Priority", question: "When approaching a roundabout, which vehicles must you give way to?", options: ["Vehicles already on the roundabout coming from your right", "Vehicles waiting to enter from the left", "Pedestrians waiting on the footpath only", "No one; vehicles entering always have priority"], answer: "A", analysis: "Drivers must give way to all traffic already on the roundabout approaching from the right before entering, as set out in the New Zealand Road Code." },
  { id: 52, type: "single", topic: "Road Signs", question: "What shape and colour is a Give Way sign in New Zealand?", options: ["Red octagon", "Red and white inverted triangle", "Yellow diamond", "Blue circle"], answer: "B", analysis: "The Give Way sign is a red-bordered inverted triangle, instructing drivers to slow down and give way to traffic and pedestrians as required." },
  { id: 53, type: "judge", topic: "Speed Limits", question: "Unless signposted otherwise, the default speed limit on New Zealand urban roads is 50 km/h.", options: [], answer: true, analysis: "In built-up urban areas, the default speed limit is 50 km/h unless a different limit is signposted." },
  { id: 54, type: "single", topic: "Drink Driving Laws", question: "What is the legal breath alcohol limit for drivers aged 20 and over in New Zealand?", options: ["Zero micrograms of alcohol per litre of breath", "400 micrograms of alcohol per litre of breath", "250 micrograms of alcohol per litre of breath", "1000 micrograms of alcohol per litre of breath"], answer: "C", analysis: "For drivers aged 20 and over, the legal breath alcohol limit is 250 micrograms per litre of breath (or 50mg of alcohol per 100ml of blood)." },
  { id: 55, type: "single", topic: "Child Car Restraints", question: "Under New Zealand law, children under what age must travel in an approved child restraint?", options: ["5 years", "10 years", "12 years", "7 years"], answer: "D", analysis: "New Zealand law requires children under 7 years old to be secured in an approved child restraint appropriate to their size." },
  { id: 56, type: "single", topic: "Motorway Emergency Procedures", question: "If your vehicle breaks down on a motorway, what should you do first?", options: ["Move to the left shoulder and turn on your hazard lights", "Stop in the traffic lane and turn on hazard lights", "Reverse carefully to the previous exit", "Continue driving slowly until you find a service station"], answer: "A", analysis: "Motorists experiencing a breakdown should move as far left as possible onto the shoulder and activate hazard lights to warn other traffic." },
  { id: 57, type: "judge", topic: "Bad Weather Driving", question: "In heavy rain, you should increase your following distance because braking distances are longer on wet roads.", options: [], answer: true, analysis: "Wet roads reduce tyre grip and increase stopping distances, so a longer following distance provides a greater safety margin." },
  { id: 58, type: "single", topic: "Crash Response", question: "What is the first action you should take immediately after being involved in a crash?", options: ["Call your insurance company before doing anything else", "Stop and check whether anyone is injured", "Leave the scene to avoid traffic delays", "Discuss who is at fault with the other driver"], answer: "B", analysis: "After any crash, drivers must stop and check for injuries before taking any other action, as required by the Road Code." },
  { id: 59, type: "single", topic: "Pedestrian & Cyclist Right of Way", question: "When turning at an intersection, who must you give way to if they are crossing the road you are turning into?", options: ["Only vehicles, not pedestrians", "No one, if your light is green", "Pedestrians who are already crossing", "Only cyclists, not pedestrians"], answer: "C", analysis: "Drivers turning at an intersection must give way to pedestrians who have already started crossing the road they are turning into." },
  { id: 60, type: "judge", topic: "Penalty Rules", question: "Accumulating 100 demerit points within a 2-year period can lead to a driver licence suspension.", options: [], answer: true, analysis: "Drivers who accumulate 100 demerit points within any 2-year period can have their licence suspended." },
  { id: 61, type: "single", topic: "Night Driving", question: "When must you turn on your vehicle's headlights according to New Zealand road rules?", options: ["Only when other vehicles are nearby", "Only on motorways", "Only when it is raining", "Between sunset and sunrise, and whenever visibility is poor"], answer: "D", analysis: "Headlights must be used from sunset to sunrise and at any other time when visibility is reduced, such as in fog or heavy rain." },
  { id: 62, type: "single", topic: "Vehicle WOF Standards", question: "What does a Warrant of Fitness (WOF) certify about a vehicle?", options: ["That it meets minimum safety standards at the time of inspection", "That it will never need repairs again", "That it is a brand-new vehicle", "That it has unlimited engine performance"], answer: "A", analysis: "A WOF confirms that a vehicle met the required minimum safety standards on the day it was inspected." },
  { id: 63, type: "judge", topic: "Roundabout Priority", question: "When you want to turn right at a roundabout, you should signal right when approaching and signal left just before exiting.", options: [], answer: true, analysis: "For a right turn at a roundabout, drivers should indicate right on approach and then change to a left signal just before leaving the roundabout." },
  { id: 64, type: "single", topic: "Road Signs", question: "A red octagonal sign displaying the word STOP means:", options: ["Slow down only if other vehicles are present", "You must come to a complete stop and give way before proceeding", "Stop only if a pedestrian is visible", "Give way only; a full stop is not required"], answer: "B", analysis: "A STOP sign requires drivers to come to a complete stop and give way to all traffic and pedestrians before continuing." },
  { id: 65, type: "single", topic: "Speed Limits", question: "What is the default open road speed limit in New Zealand unless signs indicate otherwise?", options: ["80 km/h", "90 km/h", "100 km/h", "110 km/h"], answer: "C", analysis: "Unless a different speed limit is signposted, the default open road speed limit in New Zealand is 100 km/h." },
  { id: 66, type: "single", topic: "Drink Driving Laws", question: "What is the legal alcohol limit for drivers under the age of 20 in New Zealand?", options: ["250 micrograms per litre of breath", "400 micrograms per litre of breath", "The same limit as adult drivers", "Zero alcohol"], answer: "D", analysis: "Drivers under 20 years old must have zero alcohol in their system while driving." },
  { id: 67, type: "judge", topic: "Child Car Restraints", question: "A child aged 7 but not yet 8 must use an approved child restraint if one is available in the vehicle.", options: [], answer: true, analysis: "Children aged 7 but under 8 are required to use a child restraint whenever one is available in the vehicle." },
  { id: 68, type: "single", topic: "Motorway Emergency Procedures", question: "After safely stopping on the motorway shoulder due to a breakdown, what is the recommended way to exit the vehicle?", options: ["Exit from the side away from traffic, if it is safe to do so", "Always exit from the driver's side regardless of traffic", "Remain inside with the engine running", "Exit only through the rear of the vehicle"], answer: "A", analysis: "Where possible, occupants should exit a broken-down vehicle on the side away from moving traffic for safety." },
  { id: 69, type: "single", topic: "Bad Weather Driving", question: "In foggy conditions, which lights should you use to improve visibility without dazzling other drivers?", options: ["High beam headlights at all times", "Low beam headlights and fog lights, if fitted", "Hazard lights while driving normally", "No lights, to conserve the battery"], answer: "B", analysis: "Low beam headlights, supplemented by fog lights if fitted, improve visibility in fog while reducing glare and reflection." },
  { id: 70, type: "judge", topic: "Crash Response", question: "If a crash causes injury to any person, the driver must report the crash to police as soon as possible.", options: [], answer: true, analysis: "Any crash resulting in injury must be reported to police as soon as possible, in addition to any other legal obligations." },
  { id: 71, type: "single", topic: "Pedestrian & Cyclist Right of Way", question: "If you are turning at an intersection and a cyclist is travelling straight ahead in the lane you intend to cross, what must you do?", options: ["Sound your horn and proceed", "The cyclist must give way to you", "Give way to the cyclist", "Proceed if you are travelling faster than the cyclist"], answer: "C", analysis: "Drivers turning across the path of a cyclist travelling straight ahead must give way to that cyclist." },
  { id: 72, type: "single", topic: "Penalty Rules", question: "What is a likely consequence of illegally using a mobile phone while driving in New Zealand?", options: ["No penalty if the call is brief", "Loss of vehicle registration only", "A formal warning only, with no further penalty", "An infringement fee and demerit points"], answer: "D", analysis: "Illegal use of a mobile phone while driving carries an infringement fee and demerit points under New Zealand traffic law." },
  { id: 73, type: "judge", topic: "Night Driving", question: "You should dip your headlights to low beam when an oncoming vehicle is approaching at night to avoid dazzling the other driver.", options: [], answer: true, analysis: "Dipping to low beam when meeting oncoming traffic at night prevents glare that could dazzle the other driver." },
  { id: 74, type: "single", topic: "Vehicle WOF Standards", question: "Which of the following is typically checked during a WOF inspection?", options: ["Brakes, tyres, lights, and structural condition", "Fuel economy rating only", "Interior colour and upholstery design", "Sound system quality"], answer: "A", analysis: "A WOF inspection examines key safety components such as brakes, tyres, lights, and the vehicle's structural condition." },
  { id: 75, type: "single", topic: "Roundabout Priority", question: "If you cannot see clearly to the right when approaching a roundabout, what should you do?", options: ["Enter slowly regardless of visibility", "Wait until it is safe to see clearly and enter", "Sound your horn and proceed", "Follow closely behind the vehicle ahead to merge faster"], answer: "B", analysis: "Drivers should not enter a roundabout unless they can clearly see that it is safe to do so, giving way to traffic from the right." },
  { id: 76, type: "single", topic: "Road Signs", question: "What does a yellow diamond-shaped sign typically indicate?", options: ["A compulsory direction you must follow", "Parking regulations", "A warning of a hazard or change in road conditions ahead", "The distance to the next town"], answer: "C", analysis: "Yellow diamond-shaped signs are warning signs alerting drivers to hazards or changes in road conditions ahead." },
  { id: 77, type: "judge", topic: "Speed Limits", question: "When passing a stationary emergency vehicle that has its lights flashing, you must slow down to 20 km/h while passing, where the speed limit otherwise allows.", options: [], answer: true, analysis: "New Zealand law requires drivers to slow to 20 km/h when passing a stationary emergency or service vehicle displaying flashing lights, where the posted limit is higher." },
  { id: 78, type: "single", topic: "Drink Driving Laws", question: "Exceeding which breath alcohol level can result in criminal prosecution rather than just an infringement notice?", options: ["50 micrograms per litre of breath", "100 micrograms per litre of breath", "250 micrograms per litre of breath", "400 micrograms per litre of breath"], answer: "D", analysis: "A breath alcohol level above 400 micrograms per litre is treated as a criminal offence rather than an infringement." },
  { id: 79, type: "single", topic: "Child Car Restraints", question: "From what age can a child legally use an adult seatbelt instead of a child restraint, provided no approved restraint is available?", options: ["From age 7, if a restraint is unavailable", "From age 5, in all circumstances", "Not until age 15", "Only with written permission from a doctor"], answer: "A", analysis: "A child aged 7 but under 8 may use a seatbelt instead of a child restraint only if no approved restraint is available in the vehicle." },
  { id: 80, type: "judge", topic: "Motorway Emergency Procedures", question: "You should never use the right-hand shoulder of a motorway to stop in an emergency unless absolutely no other option exists.", options: [], answer: true, analysis: "The right-hand shoulder, where it exists, is more dangerous to stop on, so it should only be used in an emergency when there is no safer alternative." },
  { id: 81, type: "single", topic: "Bad Weather Driving", question: "What is a recommended action when approaching surface flooding on a road?", options: ["Drive through quickly to avoid stalling", "Slow down and avoid driving through if the depth is uncertain", "Accelerate hard to push through the water", "Switch off your headlights to reduce distraction"], answer: "B", analysis: "Drivers should slow down and avoid entering flood water of uncertain depth, as it can cause loss of control or engine damage." },
  { id: 82, type: "single", topic: "Crash Response", question: "If you are involved in a crash with no injuries but cannot locate the other party involved, what must you do?", options: ["Do nothing further since no one was hurt", "Wait at the scene indefinitely", "Report the crash to police within 24 hours", "Only report if the damage exceeds a certain value"], answer: "C", analysis: "If you cannot find the other party after a crash, you are required to report the incident to police within 24 hours." },
  { id: 83, type: "judge", topic: "Pedestrian & Cyclist Right of Way", question: "Drivers turning into a driveway or side road must give way to pedestrians who are already crossing that driveway or side road.", options: [], answer: true, analysis: "Pedestrians who have already begun crossing a driveway or side road have right of way over a vehicle turning into it." },
  { id: 84, type: "single", topic: "Penalty Rules", question: "Which of the following is most likely to result in immediate loss of your driver licence at the roadside?", options: ["Driving 5 km/h over the speed limit", "Failing to signal on one occasion", "Having a WOF that expired the previous day", "Driving with a very high breath or blood alcohol level"], answer: "D", analysis: "Driving with a very high alcohol level can result in immediate suspension of your licence at the roadside." },
  { id: 85, type: "single", topic: "Night Driving", question: "Driving at night increases risk mainly because of:", options: ["Reduced visibility and longer reaction times to hazards", "Increased traffic volume compared to daytime", "Higher speed limits that apply at night", "Brighter glare from direct sunlight"], answer: "A", analysis: "Reduced visibility at night makes it harder to see hazards early, increasing the risk of crashes." },
  { id: 86, type: "single", topic: "Vehicle WOF Standards", question: "If your vehicle's WOF expires, what is required before it can be legally driven on public roads again (other than driving directly to a testing station)?", options: ["Nothing; an expired WOF remains valid indefinitely", "A new WOF inspection must be passed", "Only the vehicle registration needs renewing", "A verbal declaration of roadworthiness to police"], answer: "B", analysis: "A vehicle with an expired WOF must pass a new inspection before it can legally be driven on public roads, except when travelling directly to a testing station." },
  { id: 87, type: "judge", topic: "Roundabout Priority", question: "Drivers must give way to pedestrians who have already started to cross the road they are entering or leaving at a roundabout.", options: [], answer: true, analysis: "Pedestrians already crossing the road being entered or exited at a roundabout must be given way to by drivers." },
  { id: 88, type: "single", topic: "Road Signs", question: "A circular sign with a red border and a number inside generally indicates:", options: ["The number of lanes ahead", "The distance to the next exit", "A maximum speed limit in kilometres per hour", "The minimum number of passengers required"], answer: "C", analysis: "A red-bordered circular sign containing a number indicates the maximum speed limit in kilometres per hour for that section of road." },
  { id: 89, type: "single", topic: "Speed Limits", question: "Variable speed limit signs near schools typically display which reduced speed during school zone times?", options: ["30 km/h", "60 km/h", "70 km/h", "40 km/h"], answer: "D", analysis: "Variable speed limit signs near schools commonly display a reduced limit of 40 km/h during set school zone times." },
  { id: 90, type: "judge", topic: "Drink Driving Laws", question: "It is legal to drive after drinking as long as you feel capable of driving safely, regardless of measured alcohol levels.", options: [], answer: false, analysis: "Legality is determined by measured breath or blood alcohol levels, not by how capable a driver feels, so this statement is false." },
  { id: 91, type: "single", topic: "Child Car Restraints", question: "Who is primarily responsible for ensuring a child under 7 is correctly restrained while travelling in a vehicle?", options: ["The driver", "The child themselves", "Other passengers in the vehicle", "No one; it is optional"], answer: "A", analysis: "The driver is responsible for ensuring children under 7 are correctly secured in an approved child restraint." },
  { id: 92, type: "single", topic: "Motorway Emergency Procedures", question: "When a vehicle ahead on the motorway has broken down and activated its hazard lights, what should following drivers do?", options: ["Maintain the same speed and lane", "Move over to another lane if safe and reduce speed", "Overtake closely without slowing down", "Stop directly behind it to assist immediately"], answer: "B", analysis: "Drivers should move to another lane if it is safe and reduce speed when passing a broken-down vehicle with hazard lights on." },
  { id: 93, type: "judge", topic: "Bad Weather Driving", question: "Strong crosswinds have little effect on high-sided vehicles such as vans and trucks, so no extra caution is required.", options: [], answer: false, analysis: "High-sided vehicles are particularly vulnerable to strong crosswinds, so extra caution and reduced speed are recommended." },
  { id: 94, type: "single", topic: "Crash Response", question: "When approaching the scene of a crash that you are not involved in, what should you do?", options: ["Stop in the traffic lane to take photos", "Speed past the scene without slowing", "Slow down, proceed carefully, and stop to help only if needed and safe", "Sound your horn continuously to warn others"], answer: "C", analysis: "Drivers passing a crash scene should slow down, drive carefully, and only stop to assist if it is needed and safe to do so." },
  { id: 95, type: "single", topic: "Pedestrian & Cyclist Right of Way", question: "At a pedestrian crossing with no traffic lights, when must a driver stop?", options: ["Only when the pedestrian is already halfway across", "Only during daylight hours", "Only when a traffic officer is present", "When a pedestrian is on or about to step onto the crossing"], answer: "D", analysis: "Drivers must stop for a pedestrian who is on, or clearly about to step onto, a pedestrian crossing." },
  { id: 96, type: "single", topic: "Penalty Rules", question: "Why does New Zealand use a demerit point system alongside fines for traffic offences?", options: ["To track and discourage repeated offending over time", "To replace all fines completely", "To reward safe drivers with cash payments", "To register vehicles instead of drivers"], answer: "A", analysis: "The demerit point system tracks repeated offending over time and can lead to licence suspension if too many points accumulate." },
  { id: 97, type: "judge", topic: "Night Driving", question: "It is acceptable to use high beam headlights continuously when following closely behind another vehicle at night.", options: [], answer: false, analysis: "High beam headlights can dazzle the driver ahead through their mirrors, so low beam should be used when following another vehicle closely at night." },
  { id: 98, type: "single", topic: "Vehicle WOF Standards", question: "Who is responsible for ensuring a vehicle has a current WOF when required?", options: ["The Police only", "The vehicle owner", "The vehicle's manufacturer", "The original car dealer"], answer: "B", analysis: "It is the vehicle owner's responsibility to ensure their vehicle has a current WOF when one is required." },
  { id: 99, type: "single", topic: "Roundabout Priority", question: "Which lane should you generally use if you intend to continue straight ahead at a multi-lane roundabout, when road markings do not indicate otherwise?", options: ["The right lane, regardless of markings", "Either lane; lane choice never matters", "The left lane, unless markings show otherwise", "The lane closest to the centre island, regardless of exit"], answer: "C", analysis: "Unless road markings indicate otherwise, drivers travelling straight ahead at a multi-lane roundabout should generally use the left lane." },
  { id: 100, type: "judge", topic: "Road Signs", question: "Blue rectangular or square signs in New Zealand generally provide information such as facility locations or permitted actions, rather than warnings or commands.", options: [], answer: true, analysis: "Blue signs are typically informational, indicating facilities or permitted actions, distinct from warning or regulatory signs." }
];
